export const SET_USER = 'SET_USER'
export const SET_LOCALE = 'SET_LOCALE'
export const SET_LOGGED_IN = 'SET_LOGGED_IN'
export const SET_LOGIN_INFO = 'SET_LOGIN_INFO'
export const SET_THEME = 'SET_THEME'
export const SET_HEADER_ACTIVE = 'SET_HEADER_ACTIVE'
export const SET_FOOTER_ACTIVE = 'SET_FOOTER_ACTIVE'
